project:
  type: website
  render:
    - "*.qmd"
    - "!archive/"

website:
  title: "JUSMER"
  description: "Demo projects, experiments, debugging data and so on from the [Atlas of Living Australia (ALA)](https://ala.org.au/)"
  open-graph:
    image: twitter-card-preview_frog-small.png
    image-alt: "A Southern Brown Tree Frog with the ALA Labs logo"
  twitter-card:
    image: twitter-card-preview_frog-small.png
    image-alt: "A Southern Brown Tree Frog with the ALA Labs logo"
    card-style: summary_large_image
  site-url: https://tomasurzuam.github.io/web-proyecto/docs/index.html
  favicon: images/favicon.ico
  draft-mode: unlinked
  navbar:
    background: "#9B2626"
    foreground: "#FFFFFF"
    title: ""
    search: true
    logo: images/logos/jusmer_trans.png
    right:
      - href: index.qmd
        icon: house-fill
        text: " "
      - href: software/index.qmd
        text: "Proyecto"
      - href: about/index.qmd
        text: "Equipo"
      - href: posts/index.qmd
        text: "Publicaciones"
      - text: "Citaciones"
        menu:
        - href: research/citations/index.qmd
          text: "All citations"
      - href: https://www.ala.org.au
        icon: ala
      - href: https://github.com/tomasurzuam/web-proyecto
        icon: github


format:
  html:
    fontsize: 1.15rem
    monofont: Fira Code
    highlight-style: arrow
    css: [theme.css, custom_theme.scss]
    toc: true
    code-overflow: scroll
    linkcolor: "#B8573E"
    include-before-body: _fathom.html

execute:
  freeze: auto



