---
title: "Integrantes"
subtitle: Roles y afiliaciones de los miembros de JUSMER
format: 
  html: 
    include-after-body: _footer.html
title-block-banner: "#212525"
title-block-banner-color: body
---

```{r setup}
#| include: false
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
#| include: false
library(htmltools)
source("../R/functions.R")
```

# Conoce al equipo

*Click en las fotos para ver más detalles*
```{r}
#| echo: false
tags$div(class = "row",# Create a row for 3 team-member cards
         
create_team_card(
  person_page = "castillo_jc/index.html",
  img_src = "../images/people/jc.png",
  name = "Juan Carlos Castillo",
  text = "Investigador Principal"
),
create_team_card(
  person_page = "laffert_andreas/index.html",
  img_src = "../images/people/andreas.jpg",
  name = "Andreas Laffert",
  text = "Asistente de investigación"
),
create_team_card(
  person_page = "urzua_tomas/index.html",
  img_src = "../images/people/tomas.jpeg",
  name = "Tomás Urzúa",
  text = "Tesista"
)
)
tags$div(class = "row", # Create a row for 3 team-member cards
         
create_team_card(
  person_page = "canales_rene/index.html",
  img_src = "../images/people/rene.png",
  name = "René Canales",
  text = "Colaborador"
)
)
```

